import "./globals.css";

export const metadata = {
  title: "John Gerges",
  description: "Generated by create next app",
  
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
   
      </head>
      <body className="bg-gray-900 text-white antialiased font-sans">
        {children}
      </body>
    </html>
  );
}
